env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - import
rules:
  no-console: 0
  max-len: 0
  no-nested-ternary: 0
  import/extensions:
    ["error", "ignorePackages", { js: "always", mjs: "always", jsx: "always" }]
